import Vue from 'vue';
import { Button } from 'vant';
import { Icon } from 'vant';
import { Tab, Tabs } from 'vant';
import { Collapse, CollapseItem } from 'vant';
import { List } from 'vant';
import { Progress } from 'vant';
import { Sticky } from 'vant';
import { Picker } from 'vant';
import { Popup } from 'vant';
import { Area } from 'vant';
import { NavBar } from 'vant';
import { Grid, GridItem } from 'vant';
import { Search } from 'vant';
import { Field } from 'vant';
import { Cell, CellGroup } from 'vant';
import { Uploader } from 'vant';
import { Step, Steps } from 'vant';
import { Tabbar, TabbarItem } from 'vant';
import { ImagePreview } from 'vant';
import { PullRefresh } from 'vant';
import { Image } from 'vant';
import { DropdownMenu, DropdownItem } from 'vant';
import { Loading } from 'vant';
import { Toast } from 'vant';
import { Calendar } from 'vant';
import { DatetimePicker } from 'vant';
import { ActionSheet } from 'vant';
import { RadioGroup, Radio } from 'vant';
import { Checkbox, CheckboxGroup } from 'vant';
import { Dialog } from 'vant';
import { Form } from 'vant';

Vue.use(Toast);
Vue.use(Loading);
Vue.use(DropdownMenu).use(DropdownItem);
Vue.use(Image);
Vue.use(PullRefresh);
Vue.use(ImagePreview);
Vue.use(Tabbar).use(TabbarItem);
Vue.use(Step).use(Steps);
Vue.use(Uploader);
Vue.use(Cell).use(CellGroup);
Vue.use(Field);
Vue.use(Search);
Vue.use(Grid).use(GridItem);
Vue.use(NavBar);
Vue.use(Area);
Vue.use(Popup);
Vue.use(Picker);
Vue.use(Sticky);
Vue.use(Progress);
Vue.use(List)
Vue.use(Collapse).use(CollapseItem);
Vue.use(Button).use(Icon).use(Tab).use(Tabs);
Vue.use(Calendar);
Vue.use(DatetimePicker);
Vue.use(ActionSheet);
Vue.use(Radio);
Vue.use(RadioGroup);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(Dialog);
Vue.use(Form);